# Generated by Django 5.0.3 on 2024-03-31 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('canacel', models.CharField(default='0', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegModel',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('Organization_Category', models.CharField(max_length=100)),
                ('Business_Name', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=100)),
                ('States', models.CharField(max_length=100)),
                ('Cities', models.CharField(max_length=100)),
                ('Pincode', models.IntegerField(null=True)),
                ('Number', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Status', models.CharField(default='0', max_length=5)),
                ('usertype', models.CharField(default='company', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=50)),
                ('Date_Of_Birth', models.IntegerField(null=True)),
                ('Education', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Conatact_Number', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Status', models.CharField(default='0', max_length=5)),
                ('usertype', models.CharField(default='User', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewDetails',
            fields=[
                ('intrw_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('interviewDetails', models.CharField(max_length=500)),
                ('application_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.jobapplication')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.usermodel'),
        ),
        migrations.CreateModel(
            name='ComplaintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_complaints', to='resumeapp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='resumeapp.regmodel')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='resumeapp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Category', models.CharField(max_length=100)),
                ('Job_Name', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=50)),
                ('Job_Details', models.CharField(max_length=50)),
                ('Last_Date_For_Application', models.CharField(max_length=50)),
                ('regid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.regmodel')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.vacancymodel'),
        ),
    ]
