# Generated by Django 5.0.3 on 2024-04-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintmodel',
            name='reply',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
