# Generated by Django 5.0.1 on 2024-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_chatmodelanother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Date_Of_Birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='Last_Date_For_Application',
            field=models.DateField(max_length=50),
        ),
    ]
