# Generated by Django 5.0.1 on 2024-05-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_alter_usermodel_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField(max_length=250)),
                ('Phone', models.IntegerField(max_length=15)),
                ('DOB', models.DateField()),
                ('Objective', models.CharField(max_length=600)),
                ('Education', models.CharField(max_length=1080)),
                ('Experience', models.CharField(max_length=1080)),
                ('Certification', models.CharField(max_length=1080)),
                ('Skills', models.CharField(max_length=500)),
                ('Language', models.CharField(max_length=200)),
                ('Reference', models.CharField(max_length=500)),
            ],
        ),
    ]
